---
# Automated release playbook for Ansible Collections.
#
# Originally based on Ericsysmin's 2020 blog post. Meant to be used in a GitHub
# Actions CI environment.
#
# Requires a ANSIBLE_GALAXY_TOKEN secret to be configured on the GitHub repo.
#
# Usage:
#   export ANSIBLE_GALAXY_TOKEN=your_token_here if not in ~/.ansible/galaxy_token
#   ansible-playbook galaxy-deploy.yml -e "github_tag=${{ github.ref }}"

- name: Deploy new Collection version to Galaxy.
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    namespace: bluepantsdev
    collection: raspberrypi
    # Requires github_tag to be set when calling playbook.
    release_tag: "{{ github_tag.split('/')[-1] }}"

  pre_tasks:
    - name: Check if ~/.ansible/galaxy_token exists
      stat:
        path: ~/.ansible/galaxy_token
      register: galaxy_token_file

    - name: Read Galaxy token and URL from ~/.ansible/galaxy_token if it exists
      set_fact:
        galaxy_token: "{{ (lookup('file', '~/.ansible/galaxy_token') | from_yaml).token | default('') }}"
        galaxy_url: "{{ (lookup('file', '~/.ansible/galaxy_token') | from_yaml).url | default('') }}"
      when: galaxy_token_file.stat.exists

    - name: Fail if no Galaxy token is set
      fail:
        msg: A valid ANSIBLE_GALAXY_TOKEN must be set or present in ~/.ansible/galaxy_token.
      when: galaxy_token is not defined or galaxy_token | length == 0

    - name: Ensure the ~/.ansible directory exists
      file:
        path: ~/.ansible
        state: directory

    - name: Write the Galaxy token and URL to ~/.ansible/galaxy_token if not already present
      copy:
        content: |
          url: "{{ galaxy_url | default('https://galaxy.ansible.com/') }}"
          token: {{ galaxy_token }}
        dest: ~/.ansible/galaxy_token
      when: not galaxy_token_file.stat.exists

  tasks:
    - name: Ensure the galaxy.yml tag is up to date
      lineinfile:
        path: galaxy.yml
        regexp: "^version:"
        line: 'version: "{{ release_tag }}"'

    - name: Build the collection
      command: ansible-galaxy collection build
      changed_when: true

    - name: Publish the collection
      command: >
        ansible-galaxy collection publish ./{{ namespace }}-{{ collection }}-{{ release_tag }}.tar.gz
      changed_when: true
